---
# tasks file for ansible-role-free-linux-term-games
#
# determine platform to deploy on
# Supported platforms:
#   - debian
#   - ubuntu
#   - centos

- name: Deploy on Debian or Ubuntu
  include_tasks: deployonubuntu.yml
  when: ansible_os_family == "Debian"

- name: Deploy on Redhat or CentOS
  include_tasks: deployonrh.yml
  when: ansible_os_family == "RedHat"
